# Generated by Django 5.2.16 on 2026-07-07 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kernel", "0009_servicesupplier_tenant_fk"),
        ("matching", "0001_initial"),
        ("orders", "0005_tenant_foreign_keys"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("assigned", "Assigned"),
                            ("confirmed", "Confirmed"),
                            ("replaced", "Replaced"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=20,
                    ),
                ),
                (
                    "assignment_source",
                    models.CharField(
                        choices=[
                            ("matching", "Matching"),
                            ("manual", "Manual"),
                            ("api", "API"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "assignment_sequence",
                    models.IntegerField(
                        help_text="1-indexed ordinal of this assignment attempt within its Order."
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured context for this assignment attempt (replaces free-text reason).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_assignments",
                        to="matching.matchcandidate",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_assignments",
                        to="orders.order",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="booking.supplierassignment",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="kernel.servicesupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_assignments",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "booking_supplier_assignment",
                "ordering": ["-assignment_sequence"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "order", "status"],
                        name="idx_suppassign_tenant_ord_st",
                    )
                ],
                "unique_together": {("order", "assignment_sequence")},
            },
        ),
    ]
