# Generated by Django 5.2.16 on 2026-07-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("proposed", "Proposed"),
                    ("assigned", "Assigned"),
                    ("confirmed", "Confirmed"),
                    ("declined", "Declined"),
                    ("replaced", "Replaced"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="proposed",
                max_length=20,
            ),
        ),
    ]
