# Generated by Django 5.2.16 on 2026-07-12 20:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booking", "0002_alter_supplierassignment_status"),
        ("finance", "0002_settlement_idempotency_constraints"),
        ("kernel", "0011_role_assignment_active_scope_constraint"),
        ("orders", "0007_order_organization_eligibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            (
                                "PENDING_CAREGIVER_APPROVAL",
                                "Pending Caregiver Approval",
                            ),
                            ("ACTIVE", "Active"),
                            ("REJECTED", "Rejected"),
                            ("SUPERSEDED", "Superseded"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("platform_share_percent", models.PositiveSmallIntegerField()),
                ("company_share_percent", models.PositiveSmallIntegerField()),
                ("caregiver_share_percent", models.PositiveSmallIntegerField()),
                ("effective_start", models.DateTimeField(blank=True, null=True)),
                ("effective_end", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_contracts_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "caregiver_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_contracts_as_caregiver",
                        to="finance.financialparty",
                    ),
                ),
                (
                    "company_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_contracts_as_company",
                        to="finance.financialparty",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_contracts_proposed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by_contract",
                        to="commission.commissioncontract",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_contracts",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "commission_contract",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommissionSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cooperation_type", models.CharField(max_length=20)),
                (
                    "policy_source",
                    models.CharField(
                        choices=[
                            ("CONTRACT", "Active Company-Caregiver Contract"),
                            ("PLATFORM_OVERRIDE", "Platform-Specific Override"),
                            ("COOPERATION_DEFAULT", "Cooperation-Type Default"),
                            ("GLOBAL_DEFAULT", "Global Default"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "policy_version_id",
                    models.UUIDField(
                        blank=True,
                        help_text="apps.kernel.models.policy.PolicyVersion.id this snapshot was resolved from, when policy_source is not CONTRACT.",
                        null=True,
                    ),
                ),
                ("platform_rate_percent", models.PositiveSmallIntegerField()),
                ("company_rate_percent", models.PositiveSmallIntegerField(default=0)),
                ("caregiver_rate_percent", models.PositiveSmallIntegerField()),
                ("goods_platform_rate_percent", models.PositiveSmallIntegerField()),
                (
                    "goods_company_rate_percent",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("goods_caregiver_rate_percent", models.PositiveSmallIntegerField()),
                (
                    "calculation_base",
                    models.CharField(
                        choices=[("CUSTOMER_PAID_AMOUNT", "Customer-Paid Amount")],
                        default="CUSTOMER_PAID_AMOUNT",
                        max_length=30,
                    ),
                ),
                ("currency", models.CharField(default="IRR", max_length=10)),
                (
                    "rounding_policy",
                    models.CharField(default="INTEGER_IRR_FLOOR_RESIDUAL_TO_CAREGIVER", max_length=60),
                ),
                (
                    "accepted_gross_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Null in PR-A — apps.orders.Order carries no price at assignment time yet.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "discount_funding_policy",
                    models.CharField(default="PLATFORM_FUNDED", max_length=30),
                ),
                (
                    "gateway_fee_policy",
                    models.CharField(default="PLATFORM_ABSORBED", max_length=30),
                ),
                ("effective_timestamp", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "caregiver_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_snapshots_as_caregiver",
                        to="finance.financialparty",
                    ),
                ),
                (
                    "company_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_snapshots_as_company",
                        to="finance.financialparty",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="commission.commissioncontract",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_snapshots",
                        to="orders.order",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_snapshots",
                        to="kernel.servicesupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_snapshots",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "commission_snapshot",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentDeadline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_deadline_at", models.DateTimeField()),
                ("deadline_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "expiry_job_id",
                    models.UUIDField(
                        blank=True,
                        help_text="apps.jobs.models.JobDefinition.id for the scheduled expiry sweep, so extensions can reschedule it.",
                        null=True,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_deadlines",
                        to="booking.supplierassignment",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_deadlines",
                        to="orders.order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_deadlines",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "commission_payment_deadline",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentDeadlineExtension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_deadline_at", models.DateTimeField()),
                ("new_deadline_at", models.DateTimeField()),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_deadline_extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deadline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="commission.paymentdeadline",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_deadline_extensions",
                        to="orders.order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_deadline_extensions",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "commission_payment_deadline_extension",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="commissioncontract",
            index=models.Index(
                fields=["tenant", "caregiver_party", "status"],
                name="idx_commcontract_caregiver_st",
            ),
        ),
        migrations.AddIndex(
            model_name="commissioncontract",
            index=models.Index(
                fields=["tenant", "company_party", "status"],
                name="idx_commcontract_company_st",
            ),
        ),
        migrations.AddIndex(
            model_name="commissionsnapshot",
            index=models.Index(fields=["tenant", "order"], name="idx_commsnap_tenant_order"),
        ),
        migrations.AddIndex(
            model_name="paymentdeadline",
            index=models.Index(fields=["tenant", "order", "status"], name="idx_paydeadline_ord_st"),
        ),
        migrations.AddIndex(
            model_name="paymentdeadline",
            index=models.Index(fields=["status", "deadline_at"], name="idx_paydeadline_status_due"),
        ),
    ]
