# Generated by Django 5.2.16 on 2026-07-12 22:07

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commission", "0001_initial"),
        ("finance", "0002_settlement_idempotency_constraints"),
        ("kernel", "0011_role_assignment_active_scope_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="commissioncontract",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["DRAFT", "PENDING_CAREGIVER_APPROVAL"])),
                fields=("tenant", "company_party", "caregiver_party"),
                name="uq_commcontract_open_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="commissioncontract",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("tenant", "company_party", "caregiver_party"),
                name="uq_commcontract_active_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="commissioncontract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("platform_share_percent__gte", 0),
                    ("platform_share_percent__lte", 100),
                    ("company_share_percent__gte", 0),
                    ("company_share_percent__lte", 100),
                    ("caregiver_share_percent__gte", 0),
                    ("caregiver_share_percent__lte", 100),
                ),
                name="chk_commcontract_share_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="commissioncontract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "platform_share_percent",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.Value(100),
                                "-",
                                models.F("company_share_percent"),
                            ),
                            "-",
                            models.F("caregiver_share_percent"),
                        ),
                    )
                ),
                name="chk_commcontract_shares_sum100",
            ),
        ),
    ]
