# Generated by Django 5.2.16 on 2026-07-13 04:48

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commission", "0002_commissioncontract_uq_commcontract_open_pair_and_more"),
        ("execution", "0001_initial"),
        ("finance", "0003_escrowmovement_escrowrecord_blocked_amount_irr_and_more"),
        ("kernel", "0011_role_assignment_active_scope_constraint"),
        ("orders", "0007_order_organization_eligibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("disputed_amount_irr", models.PositiveBigIntegerField()),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("SERVICE_NOT_PERFORMED", "Service Not Performed"),
                            ("SERVICE_QUALITY", "Service Quality"),
                            ("INCORRECT_AMOUNT", "Incorrect Amount"),
                            ("DURATION_MISMATCH", "Duration Mismatch"),
                            ("UNAUTHORIZED_EXTRA_CHARGE", "Unauthorized Extra Charge"),
                            ("OTHER", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("evidence_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("PARTIALLY_RESOLVED", "Partially Resolved"),
                            ("RESOLVED", "Resolved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("resolution_type", models.CharField(blank=True, max_length=40)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes_as_customer",
                        to="finance.financialparty",
                    ),
                ),
                (
                    "escrow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="finance.escrowrecord",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="finance.financialdocument",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="orders.order",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes_as_supplier",
                        to="finance.financialparty",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "commission_dispute",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("disputed_amount_irr", models.PositiveBigIntegerField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("evidence_reference", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="commission.dispute",
                    ),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute_lines",
                        to="finance.financialdocumentitem",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute_lines",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "commission_dispute_line",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeResolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_blocked_amount_irr", models.PositiveBigIntegerField()),
                (
                    "customer_refund_amount_irr",
                    models.PositiveBigIntegerField(default=0),
                ),
                ("platform_amount_irr", models.PositiveBigIntegerField(default=0)),
                ("company_amount_irr", models.PositiveBigIntegerField(default=0)),
                ("caregiver_amount_irr", models.PositiveBigIntegerField(default=0)),
                ("reason", models.TextField()),
                ("resolved_at", models.DateTimeField(auto_now_add=True)),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=255)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commission_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute_resolutions",
                        to="commission.commissionsnapshot",
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolutions",
                        to="commission.dispute",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute_resolutions",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "commission_dispute_resolution",
                "ordering": ["-resolved_at"],
            },
        ),
        migrations.CreateModel(
            name="ObjectionPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("OPEN", "Open"),
                            ("CUSTOMER_APPROVED", "Customer Approved"),
                            ("AUTO_APPROVED", "Auto Approved"),
                            ("DISPUTED", "Disputed"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("completion_at", models.DateTimeField()),
                ("objection_deadline", models.DateTimeField()),
                ("customer_approved_at", models.DateTimeField(blank=True, null=True)),
                ("auto_approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approval_source",
                    models.CharField(
                        blank=True,
                        choices=[("CUSTOMER", "Customer"), ("AUTO", "Auto")],
                        max_length=20,
                    ),
                ),
                ("auto_approve_job_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "escrow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="objection_periods",
                        to="finance.escrowrecord",
                    ),
                ),
                (
                    "execution_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="objection_periods",
                        to="execution.executionsession",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="objection_periods",
                        to="orders.order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="objection_periods",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "commission_objection_period",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ObjectionPeriodExtension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_deadline_at", models.DateTimeField()),
                ("new_deadline_at", models.DateTimeField()),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "objection_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="commission.objectionperiod",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="objection_period_extensions",
                        to="orders.order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="objection_period_extensions",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "commission_objection_period_extension",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefundInstruction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_irr", models.PositiveBigIntegerField()),
                ("reason", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("DISPUTE_RESOLUTION", "Dispute Resolution"),
                            ("CANCELLATION", "Cancellation"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("INITIATED", "Initiated"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("psp_reference", models.CharField(blank=True, max_length=255)),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dispute_resolution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_instructions",
                        to="commission.disputeresolution",
                    ),
                ),
                (
                    "escrow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_instructions",
                        to="finance.escrowrecord",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_instructions",
                        to="finance.financialdocument",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_instructions",
                        to="orders.order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_instructions",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "commission_refund_instruction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseInstruction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("CUSTOMER_APPROVAL", "Customer Approval"),
                            ("AUTO_APPROVAL", "Auto Approval"),
                            ("UNDISPUTED_PARTIAL", "Undisputed Partial Release"),
                            ("DISPUTE_RESOLUTION", "Dispute Resolution"),
                        ],
                        max_length=30,
                    ),
                ),
                ("gross_releasable_amount_irr", models.PositiveBigIntegerField()),
                ("currency", models.CharField(default="IRR", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_ALLOCATION", "Pending Allocation"),
                            ("READY", "Ready"),
                            ("CONSUMED", "Consumed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="READY",
                        max_length=20,
                    ),
                ),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commission_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_instructions",
                        to="commission.commissionsnapshot",
                    ),
                ),
                (
                    "dispute_resolution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_instructions",
                        to="commission.disputeresolution",
                    ),
                ),
                (
                    "escrow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_instructions",
                        to="finance.escrowrecord",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_instructions",
                        to="finance.financialdocument",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_instructions",
                        to="orders.order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_instructions",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "commission_release_instruction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["tenant", "order", "status"], name="idx_dispute_tenant_ord_st"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["tenant", "escrow", "status"], name="idx_dispute_tenant_esc_st"),
        ),
        migrations.AddConstraint(
            model_name="dispute",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("tenant", "idempotency_key"),
                name="uq_dispute_tenant_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispute",
            constraint=models.CheckConstraint(
                condition=models.Q(("disputed_amount_irr__gt", 0)),
                name="chk_dispute_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="disputeline",
            constraint=models.CheckConstraint(
                condition=models.Q(("disputed_amount_irr__gt", 0)),
                name="chk_disputeline_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="disputeresolution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("tenant", "idempotency_key"),
                name="uq_disputeres_tenant_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="disputeresolution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_blocked_amount_irr",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    models.F("customer_refund_amount_irr"),
                                    "+",
                                    models.F("platform_amount_irr"),
                                ),
                                "+",
                                models.F("company_amount_irr"),
                            ),
                            "+",
                            models.F("caregiver_amount_irr"),
                        ),
                    )
                ),
                name="chk_disputeres_conservation",
            ),
        ),
        migrations.AddIndex(
            model_name="objectionperiod",
            index=models.Index(fields=["tenant", "order", "status"], name="idx_objperiod_tenant_ord_st"),
        ),
        migrations.AddIndex(
            model_name="refundinstruction",
            index=models.Index(
                fields=["tenant", "escrow", "status"],
                name="idx_refundinstr_tenant_esc_st",
            ),
        ),
        migrations.AddConstraint(
            model_name="refundinstruction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("tenant", "idempotency_key"),
                name="uq_refundinstr_tenant_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="refundinstruction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_irr__gt", 0)),
                name="chk_refundinstr_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="releaseinstruction",
            index=models.Index(fields=["tenant", "escrow", "status"], name="idx_relinstr_tenant_esc_st"),
        ),
        migrations.AddConstraint(
            model_name="releaseinstruction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("tenant", "idempotency_key"),
                name="uq_relinstr_tenant_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="releaseinstruction",
            constraint=models.CheckConstraint(
                condition=models.Q(("gross_releasable_amount_irr__gt", 0)),
                name="chk_relinstr_amount_positive",
            ),
        ),
    ]
