# Generated by Django 5.2.16 on 2026-07-08 20:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("kernel", "0009_servicesupplier_tenant_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="IRR", max_length=10)),
                (
                    "provider",
                    models.CharField(
                        choices=[("FAKE", "Fake (test/internal)")],
                        default="FAKE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("PENDING", "Pending"),
                            ("AUTHORIZED", "Authorized"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255)),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Generic tag for what this payment is for, e.g. 'Order', 'Quote'. No FK — decoupled by design.",
                        max_length=100,
                    ),
                ),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payer_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_intents",
                        to="finance.financialparty",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_intents",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment_intent",
                "ordering": ["-created_at"],
                "unique_together": {("tenant", "idempotency_key")},
            },
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(choices=[("FAKE", "Fake (test/internal)")], max_length=20),
                ),
                ("provider_reference", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("PENDING", "Pending"),
                            ("AUTHORIZED", "Authorized"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("request_snapshot", models.JSONField(blank=True, default=dict)),
                ("response_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_attempts",
                        to="kernel.tenant",
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="payments.paymentintent",
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment_attempt",
                "ordering": ["-created_at"],
                "unique_together": {("tenant", "provider_reference")},
            },
        ),
        migrations.CreateModel(
            name="PaymentCallback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_event_id",
                    models.CharField(
                        help_text="Provider-supplied idempotency identifier for this callback.",
                        max_length=255,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("accepted", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "resulting_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CREATED", "Created"),
                            ("PENDING", "Pending"),
                            ("AUTHORIZED", "Authorized"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="callbacks",
                        to="payments.paymentattempt",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_callbacks",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment_callback",
                "ordering": ["-created_at"],
                "unique_together": {("attempt", "provider_event_id")},
            },
        ),
    ]
