# Generated by Django 5.2.16 on 2026-07-09 06:11

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kernel", "0009_servicesupplier_tenant_fk"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.IntegerField()),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("EMAIL", "Email"),
                            ("PUSH", "Push"),
                            ("IN_APP", "In-App"),
                        ],
                        max_length=10,
                    ),
                ),
                ("provider_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DISPATCHING", "Dispatching"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("DEAD_LETTER", "Dead Letter"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("error_message", models.TextField(blank=True)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "notifications_delivery_attempt",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="max_retries",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="notification",
            name="next_attempt_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Next time the dispatcher should attempt delivery.",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("DISPATCHING", "Dispatching"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                    ("DEAD_LETTER", "Dead Letter"),
                ],
                db_index=True,
                default="PENDING",
                max_length=15,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["status", "next_attempt_at"], name="idx_notif_due"),
        ),
        migrations.AddField(
            model_name="notificationdeliveryattempt",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_attempts",
                to="notifications.notification",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdeliveryattempt",
            index=models.Index(fields=["notification", "attempted_at"], name="idx_notif_attempt_notif"),
        ),
    ]
