# Generated by Django 5.2.16 on 2026-07-09 05:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Null means a global/system job.",
                        null=True,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        db_index=True,
                        help_text="Registry key looked up to find the handler.",
                        max_length=200,
                    ),
                ),
                (
                    "queue_name",
                    models.CharField(db_index=True, default="default", max_length=100),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True,
                        help_text="Enqueuing with an existing (tenant_id, job_type, idempotency_key) reuses the existing job.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("dead_letter", "Dead Letter"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Earliest time this job may first run.",
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Next time the runner should attempt this job.",
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("last_error", models.TextField(blank=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Job Definition",
                "verbose_name_plural": "Job Definitions",
                "db_table": "jobs_job_definition",
                "ordering": ["next_run_at"],
                "indexes": [
                    models.Index(fields=["status", "next_run_at"], name="idx_job_due"),
                    models.Index(
                        fields=["tenant_id", "job_type", "created_at"],
                        name="idx_job_tenant_type",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "job_type", "idempotency_key"),
                        name="uq_job_tenant_type_idempotency",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("dead_letter", "Dead Letter"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="jobs.jobdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Run",
                "verbose_name_plural": "Job Runs",
                "db_table": "jobs_job_run",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["job", "started_at"], name="idx_job_run_job_started"
                    )
                ],
            },
        ),
    ]
