# Generated by Django 5.2.16 on 2026-07-07 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kernel", "0009_servicesupplier_tenant_fk"),
        ("orders", "0005_tenant_foreign_keys"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "config_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of matching configuration at run time (immune to later config changes).",
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_rounds",
                        to="orders.order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_rounds",
                        to="kernel.tenant",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "matching_round",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("eligible", models.BooleanField(default=False)),
                (
                    "eligibility_code",
                    models.CharField(
                        choices=[
                            ("eligible", "Eligible"),
                            ("wrong_tenant", "Wrong Tenant"),
                            ("supplier_not_active", "Supplier Not Active"),
                            ("supplier_unavailable", "Supplier Unavailable"),
                            ("category_not_supported", "Category Not Supported"),
                            (
                                "supplier_type_not_allowed",
                                "Supplier Type Not Allowed by Marketplace Model",
                            ),
                            (
                                "below_verification_threshold",
                                "Below Minimum Verification Level",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "eligibility_reason",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured explanation for the eligibility_code (ADR-02-07: explainable eligibility).",
                    ),
                ),
                (
                    "rank_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "score_breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-component contributions to rank_score, for transparency/debugging.",
                    ),
                ),
                ("rank_position", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("ranked", "Ranked"),
                            ("presented", "Presented"),
                            ("selected", "Selected"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="generated",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_candidacies",
                        to="kernel.servicesupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_candidates",
                        to="kernel.tenant",
                    ),
                ),
                (
                    "match_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="matching.matchround",
                    ),
                ),
            ],
            options={
                "db_table": "matching_candidate",
                "ordering": ["rank_position", "-rank_score"],
            },
        ),
        migrations.AddIndex(
            model_name="matchround",
            index=models.Index(
                fields=["tenant", "order", "status"],
                name="idx_matchround_tenant_order_st",
            ),
        ),
        migrations.AddIndex(
            model_name="matchcandidate",
            index=models.Index(
                fields=["tenant", "match_round", "eligible"],
                name="idx_mcand_tenant_round_elig",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchcandidate",
            unique_together={("match_round", "supplier")},
        ),
    ]
