# Generated by Django 5.2.16 on 2026-07-08 14:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kernel", "0009_servicesupplier_tenant_fk"),
        ("orders", "0005_tenant_foreign_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("FIXED_AMOUNT", "Fixed Amount"),
                            ("HOURLY_RATE", "Hourly Rate"),
                            ("PERCENTAGE_ADJUSTMENT", "Percentage Adjustment"),
                            ("FLAT_SURCHARGE", "Flat Surcharge"),
                            ("TIME_OF_DAY_SURCHARGE", "Time-of-Day Surcharge"),
                            ("WEEKEND_SURCHARGE", "Weekend Surcharge"),
                            ("HOLIDAY_SURCHARGE", "Holiday Surcharge"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                ("time_start", models.TimeField(blank=True, null=True)),
                ("time_end", models.TimeField(blank=True, null=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Lower runs first. Ties broken by created_at, then id.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("currency", models.CharField(default="IRR", max_length=10)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pricing_rules",
                        to="orders.servicecategory",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="kernel.servicesupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pricing_rules",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_rule",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "stackable",
                    models.BooleanField(
                        default=False,
                        help_text="If False, applying this promotion stops any further (lower-priority) promotions from applying.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Lower runs first. Ties broken by created_at, then id.",
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_promotion",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("FIRST_ORDER_ONLY", "First Order Only"),
                            ("SERVICE_CATEGORY", "Service Category"),
                            ("SUPPLIER", "Supplier"),
                            ("MIN_AMOUNT", "Minimum Amount"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="pricing.promotion",
                    ),
                ),
                (
                    "service_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orders.servicecategory",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="kernel.servicesupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_conditions",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_promotion_condition",
            },
        ),
        migrations.CreateModel(
            name="PromotionEffect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "effect_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE_DISCOUNT", "Percentage Discount"),
                            ("FIXED_DISCOUNT", "Fixed Discount"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effects",
                        to="pricing.promotion",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_effects",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_promotion_effect",
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("EXPIRED", "Expired")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="IRR", max_length=10)),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "surcharge_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The point in time pricing was evaluated against (time-of-day/weekend/holiday rules).",
                        null=True,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("pricing_snapshot", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="orders.order",
                    ),
                ),
                (
                    "service_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="orders.servicecategory",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="kernel.servicesupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_quote",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("BASE", "Base"),
                            ("PRICING_RULE", "Pricing Rule"),
                            ("PROMOTION", "Promotion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("sequence", models.IntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="pricing.quote",
                    ),
                ),
                (
                    "source_promotion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_lines",
                        to="pricing.promotion",
                    ),
                ),
                (
                    "source_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_lines",
                        to="pricing.pricingrule",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_lines",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "pricing_quote_line",
                "ordering": ["sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="pricingrule",
            index=models.Index(
                fields=["tenant", "rule_type", "is_active"],
                name="idx_pricerule_tenant_type_st",
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["tenant", "order"], name="idx_quote_tenant_order"
            ),
        ),
    ]
