# Generated by Django 5.2.16 on 2026-07-08 14:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("kernel", "0009_servicesupplier_tenant_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapacityRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("max_concurrent_assignments", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity_rule",
                        to="kernel.servicesupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capacity_rules",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "availability_capacity_rule",
            },
        ),
        migrations.CreateModel(
            name="AvailabilityBlockedPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("LEAVE", "Leave"),
                            ("SICK", "Sick"),
                            ("HOLIDAY", "Holiday"),
                            ("MANUAL_BLOCK", "Manual Block"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_periods",
                        to="kernel.servicesupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="availability_blocked_periods",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "availability_blocked_period",
                "ordering": ["start_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "supplier", "start_at", "end_at"],
                        name="idx_blockperiod_sup_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderWorkingWindow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_windows",
                        to="kernel.servicesupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_working_windows",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "availability_working_window",
                "ordering": ["day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "supplier", "day_of_week"],
                        name="idx_workwin_tenant_sup_day",
                    )
                ],
            },
        ),
    ]
