# Generated by Django 5.2.16 on 2026-07-08 05:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("execution", "0001_initial"),
        ("kernel", "0009_servicesupplier_tenant_fk"),
        ("orders", "0005_tenant_foreign_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("INVOICE", "Invoice"),
                            ("SUPPLEMENTAL_INVOICE", "Supplemental Invoice"),
                            ("CREDIT_NOTE", "Credit Note"),
                            ("DEBIT_NOTE", "Debit Note"),
                            ("REFUND_NOTE", "Refund Note"),
                            ("MANUAL_ADJUSTMENT", "Manual Adjustment"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("LOCKED", "Locked"),
                            ("CANCELLED", "Cancelled"),
                            ("VOIDED", "Voided"),
                            ("PAID", "Paid"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("DISPUTED", "Disputed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="IRR", max_length=10)),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("pricing_snapshot", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "execution_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_documents",
                        to="execution.executionsession",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_documents",
                        to="orders.order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_documents",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "finance_financial_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialDocumentItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("SERVICE", "Service"),
                            ("TRAVEL", "Travel"),
                            ("GOODS", "Goods"),
                            ("EXTRA_SERVICE", "Extra Service"),
                            ("OVERTIME", "Overtime"),
                            ("DISCOUNT", "Discount"),
                            ("TAX", "Tax"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=10
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.financialdocument",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_document_items",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "finance_financial_document_item",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialParty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "linked_entity_type",
                    models.CharField(
                        help_text="Type of the linked operational entity, e.g. 'ServiceSupplier', 'CustomerProfile', 'Tenant'.",
                        max_length=100,
                    ),
                ),
                (
                    "linked_entity_id",
                    models.UUIDField(help_text="ID of the linked operational entity."),
                ),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "Customer"),
                            ("SUPPLIER", "Supplier"),
                            ("PLATFORM", "Platform"),
                            ("ORGANIZATION", "Organization"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_parties",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "finance_financial_party",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="FinancialObligation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="IRR", max_length=10)),
                (
                    "obligation_type",
                    models.CharField(
                        choices=[
                            ("INVOICE_PAYMENT", "Invoice Payment"),
                            ("REFUND", "Refund"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("COMMISSION", "Commission"),
                        ],
                        default="INVOICE_PAYMENT",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("DUE", "Due"),
                            ("PARTIALLY_RESOLVED", "Partially Resolved"),
                            ("RESOLVED", "Resolved"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed"),
                            ("DISPUTED", "Disputed"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligations",
                        to="finance.financialdocument",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_obligations",
                        to="kernel.tenant",
                    ),
                ),
                (
                    "creditor_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligations_receivable",
                        to="finance.financialparty",
                    ),
                ),
                (
                    "debtor_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligations_owed",
                        to="finance.financialparty",
                    ),
                ),
            ],
            options={
                "db_table": "finance_financial_obligation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="financialdocument",
            name="beneficiary_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beneficiary_documents",
                to="finance.financialparty",
            ),
        ),
        migrations.AddField(
            model_name="financialdocument",
            name="issuer_party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issued_documents",
                to="finance.financialparty",
            ),
        ),
        migrations.AddField(
            model_name="financialdocument",
            name="payer_party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payable_documents",
                to="finance.financialparty",
            ),
        ),
        migrations.CreateModel(
            name="EscrowRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="IRR", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HELD", "Held"),
                            ("RELEASED", "Released"),
                            ("REFUNDED", "Refunded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="HELD",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrow_records",
                        to="kernel.tenant",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrow_records",
                        to="finance.financialdocument",
                    ),
                ),
                (
                    "beneficiary_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escrow_as_beneficiary",
                        to="finance.financialparty",
                    ),
                ),
                (
                    "payer_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrow_as_payer",
                        to="finance.financialparty",
                    ),
                ),
            ],
            options={
                "db_table": "finance_escrow_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="IRR", max_length=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("CASH", "Cash"),
                            ("CARD_TO_CARD", "Card to Card"),
                            ("WALLET", "Wallet"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=255)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collected_by_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collected_payments",
                        to="finance.financialparty",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="finance.financialobligation",
                    ),
                ),
                (
                    "payer_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments_made",
                        to="finance.financialparty",
                    ),
                ),
                (
                    "receiver_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments_received",
                        to="finance.financialparty",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="finance.financialdocument",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "finance_payment_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_group_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Groups the balanced set of debit/credit entries posted together.",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        max_length=10,
                    ),
                ),
                ("account_code", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="IRR", max_length=10)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "obligation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="finance.financialobligation",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="finance.financialparty",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="finance.financialdocument",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="kernel.tenant",
                    ),
                ),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="finance.paymenttransaction",
                    ),
                ),
            ],
            options={
                "db_table": "finance_ledger_entry",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SettlementBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CALCULATED", "Calculated"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="IRR", max_length=10)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_batches",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "finance_settlement_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SettlementItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="IRR", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.settlementbatch",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_items",
                        to="finance.financialparty",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_items",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "finance_settlement_item",
                "ordering": ["party_id"],
            },
        ),
        migrations.CreateModel(
            name="WalletAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("currency", models.CharField(default="IRR", max_length=10)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("CLOSED", "Closed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallets",
                        to="finance.financialparty",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet_accounts",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "finance_wallet_account",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("CREDIT", "Credit"),
                            ("DEBIT", "Debit"),
                            ("HOLD", "Hold"),
                            ("RELEASE", "Release"),
                            ("REFUND", "Refund"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=14)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions",
                        to="finance.paymenttransaction",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions",
                        to="finance.financialdocument",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet_transactions",
                        to="kernel.tenant",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finance.walletaccount",
                    ),
                ),
            ],
            options={
                "db_table": "finance_wallet_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="financialparty",
            index=models.Index(
                fields=["tenant", "party_type", "status"],
                name="idx_finparty_tenant_type_st",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="financialparty",
            unique_together={
                ("tenant", "linked_entity_type", "linked_entity_id", "party_type")
            },
        ),
        migrations.AddIndex(
            model_name="financialobligation",
            index=models.Index(
                fields=["tenant", "status"], name="idx_finoblig_tenant_status"
            ),
        ),
        migrations.AddIndex(
            model_name="financialdocument",
            index=models.Index(
                fields=["tenant", "document_type", "status"],
                name="idx_findoc_tenant_type_st",
            ),
        ),
        migrations.AddIndex(
            model_name="financialdocument",
            index=models.Index(
                fields=["tenant", "execution_session"],
                name="idx_findoc_tenant_execsess",
            ),
        ),
        migrations.AddIndex(
            model_name="escrowrecord",
            index=models.Index(
                fields=["tenant", "status"], name="idx_finescrow_tenant_status"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["tenant", "status"], name="idx_finpay_tenant_status"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["tenant", "entry_group_id"], name="idx_finledger_tenant_group"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["tenant", "party", "account_code"],
                name="idx_finledger_party_acct",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="settlementitem",
            unique_together={("batch", "party")},
        ),
        migrations.AlterUniqueTogether(
            name="walletaccount",
            unique_together={("tenant", "party", "currency")},
        ),
    ]
