# Generated by Django 5.2.16 on 2026-07-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
        ("kernel", "0010_useraccount_email_unique"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("payment_transaction__isnull", False)),
                fields=("payment_transaction", "account_code"),
                name="uq_ledger_entry_payment_txn_account_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_reference__gt", "")),
                fields=("tenant", "provider_reference"),
                name="uq_payment_transaction_tenant_provider_reference",
            ),
        ),
    ]
