# Generated by Django 5.2.16 on 2026-07-13 04:46

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commission", "0002_commissioncontract_uq_commcontract_open_pair_and_more"),
        ("finance", "0002_settlement_idempotency_constraints"),
        ("kernel", "0011_role_assignment_active_scope_constraint"),
        ("orders", "0007_order_organization_eligibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EscrowMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("HOLD", "Hold"),
                            ("MARK_RELEASABLE", "Mark Releasable"),
                            ("BLOCK_FOR_DISPUTE", "Block For Dispute"),
                            ("UNBLOCK", "Unblock"),
                            ("RELEASE", "Release"),
                            ("REFUND", "Refund"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("amount_irr", models.PositiveBigIntegerField()),
                ("before_state", models.JSONField(default=dict)),
                ("after_state", models.JSONField(default=dict)),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        help_text="What caused this movement, e.g. 'ObjectionPeriod', 'Dispute', 'DisputeResolution'.",
                        max_length=100,
                    ),
                ),
                ("source_id", models.UUIDField(blank=True, null=True)),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=255)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_escrow_movement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="escrowrecord",
            name="blocked_amount_irr",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="escrowrecord",
            name="commission_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="escrow_records",
                to="commission.commissionsnapshot",
            ),
        ),
        migrations.AddField(
            model_name="escrowrecord",
            name="correlation_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrowrecord",
            name="held_amount_irr",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="escrowrecord",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="escrowrecord",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="escrow_records",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="escrowrecord",
            name="original_amount_irr",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="escrowrecord",
            name="payment_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="escrow_records",
                to="finance.paymenttransaction",
            ),
        ),
        migrations.AddField(
            model_name="escrowrecord",
            name="refunded_amount_irr",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="escrowrecord",
            name="releasable_amount_irr",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="escrowrecord",
            name="released_amount_irr",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="escrowrecord",
            name="remaining_amount_irr",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="escrowrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("HELD", "Held"),
                    ("RELEASED", "Released"),
                    ("REFUNDED", "Refunded"),
                    ("CANCELLED", "Cancelled"),
                    ("PARTIALLY_RELEASED", "Partially Released"),
                    ("FULLY_RELEASED", "Fully Released"),
                    ("PARTIALLY_REFUNDED", "Partially Refunded"),
                    ("FULLY_REFUNDED", "Fully Refunded"),
                    ("CLOSED", "Closed"),
                ],
                db_index=True,
                default="HELD",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="escrowrecord",
            index=models.Index(
                fields=["tenant", "order", "status"],
                name="idx_finescrow_tenant_order_st",
            ),
        ),
        migrations.AddConstraint(
            model_name="escrowrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("tenant", "idempotency_key"),
                name="uq_escrow_tenant_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="escrowrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "original_amount_irr",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    models.F("released_amount_irr"),
                                    "+",
                                    models.F("refunded_amount_irr"),
                                ),
                                "+",
                                models.F("blocked_amount_irr"),
                            ),
                            "+",
                            models.F("remaining_amount_irr"),
                        ),
                    )
                ),
                name="chk_escrow_conservation",
            ),
        ),
        migrations.AddConstraint(
            model_name="escrowrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "held_amount_irr",
                        django.db.models.expressions.CombinedExpression(
                            models.F("blocked_amount_irr"),
                            "+",
                            models.F("remaining_amount_irr"),
                        ),
                    )
                ),
                name="chk_escrow_held_derived",
            ),
        ),
        migrations.AddConstraint(
            model_name="escrowrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("releasable_amount_irr__lte", models.F("remaining_amount_irr"))),
                name="chk_escrow_releasable_within_remaining",
            ),
        ),
        migrations.AddField(
            model_name="escrowmovement",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="escrowmovement",
            name="escrow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="finance.escrowrecord",
            ),
        ),
        migrations.AddField(
            model_name="escrowmovement",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="escrow_movements",
                to="kernel.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="escrowmovement",
            index=models.Index(
                fields=["tenant", "escrow", "movement_type"],
                name="idx_escrowmove_tenant_esc_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="escrowmovement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("tenant", "idempotency_key"),
                name="uq_escrowmovement_tenant_idempotency",
            ),
        ),
    ]
