# Generated by Django 5.2.16 on 2026-07-08 04:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        ("kernel", "0009_servicesupplier_tenant_fk"),
        ("orders", "0005_tenant_foreign_keys"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("provider_completed", "Provider Completed"),
                            ("customer_pending", "Customer Pending"),
                            ("closed", "Closed"),
                            ("paused", "Paused"),
                            ("interrupted", "Interrupted"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "execution_source",
                    models.CharField(
                        choices=[
                            ("booking", "Booking"),
                            ("manual", "Manual"),
                            ("system", "System"),
                            ("recovery", "Recovery"),
                            ("api", "API"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "execution_sequence",
                    models.IntegerField(help_text="1-indexed ordinal of this execution attempt within its Order."),
                ),
                (
                    "context_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of execution configuration/context at session creation time.",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("provider_completed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_sessions",
                        to="orders.order",
                    ),
                ),
                (
                    "supplier_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_sessions",
                        to="booking.supplierassignment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_sessions",
                        to="kernel.tenant",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "execution_session",
                "ordering": ["-execution_sequence"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "order", "status"],
                        name="idx_execsession_tenant_ord_st",
                    )
                ],
                "unique_together": {("order", "execution_sequence")},
            },
        ),
    ]
