# Generated by Django 5.2.16 on 2026-07-08 18:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("kernel", "0009_servicesupplier_tenant_fk"),
        ("orders", "0005_tenant_foreign_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReputationSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                (
                    "average_score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
                ),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_snapshot",
                        to="kernel.servicesupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reputation_snapshots",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_reputation_snapshot",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reviewer_person_id",
                    models.UUIDField(help_text="kernel.Person id of the reviewer."),
                ),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("moderation_reason", models.TextField(blank=True)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                ("overall_rating", models.DecimalField(decimal_places=2, max_digits=3)),
                ("written_text", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="orders.order",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="kernel.servicesupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("QUALITY", "Quality"),
                            ("PUNCTUALITY", "Punctuality"),
                            ("PROFESSIONALISM", "Professionalism"),
                            ("COMMUNICATION", "Communication"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="reviews.review",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_ratings",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_review_rating",
            },
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["tenant", "supplier", "moderation_status"],
                name="idx_review_tenant_sup_mod",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("order", "supplier")},
        ),
        migrations.AlterUniqueTogether(
            name="reviewrating",
            unique_together={("review", "dimension")},
        ),
    ]
