# Generated by Django 5.2.16 on 2026-07-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profiles_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="elderprofile",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="elderprofile",
            name="communication_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="elderprofile",
            name="disabilities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="elderprofile",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="elderprofile",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="elderprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="elderprofile",
            name="preferred_caregiver_gender",
            field=models.CharField(
                choices=[
                    ("no_preference", "No Preference"),
                    ("male", "Male"),
                    ("female", "Female"),
                ],
                default="no_preference",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="elderprofile",
            name="preferred_language",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="elderprofile",
            name="relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("self", "Self"),
                    ("father", "Father"),
                    ("mother", "Mother"),
                    ("spouse", "Spouse"),
                    ("child", "Child"),
                    ("sibling", "Sibling"),
                    ("grandparent", "Grandparent"),
                    ("relative", "Relative"),
                    ("friend", "Friend"),
                    ("legal_guardian", "Legal Guardian"),
                    ("other", "Other"),
                ],
                help_text="The requesting customer's relationship to this care recipient.",
                max_length=20,
            ),
        ),
    ]
