# Generated by Django 5.2.16 on 2026-07-11 14:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models.media_paths


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_elderprofile_allergies_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.accounts.models.media_paths.caregiver_avatar_path,
            ),
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.accounts.models.media_paths.caregiver_cover_path,
            ),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.accounts.models.media_paths.organization_cover_path,
            ),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.accounts.models.media_paths.organization_logo_path,
            ),
        ),
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("identity", "Identity"),
                            ("background_check", "Background Check"),
                            ("qualification", "Qualification"),
                            ("training_certificate", "Training Certificate"),
                            ("license", "License"),
                            ("registration", "Registration"),
                            ("operating_license", "Operating License"),
                            ("insurance", "Insurance"),
                            ("professional_permit", "Professional Permit"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=apps.accounts.models.media_paths.verification_document_path),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "caregiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.caregiverprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.organizationprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_verification_document",
                "indexes": [
                    models.Index(
                        fields=["caregiver", "document_type"],
                        name="accounts_ve_caregiv_ce7fc1_idx",
                    ),
                    models.Index(
                        fields=["organization", "document_type"],
                        name="accounts_ve_organiz_b21aaf_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("caregiver__isnull", False),
                                ("organization__isnull", True),
                            ),
                            models.Q(
                                ("caregiver__isnull", True),
                                ("organization__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="verification_document_exactly_one_owner",
                    )
                ],
            },
        ),
    ]
