# Generated by Django 5.2.16 on 2026-07-15 04:55
# Hand-trimmed: makemigrations also detected pre-existing, unrelated
# cosmetic field drift (bio/caregiver_note/organization/reviewer_note/
# notes/address/code/description — see project docs/quality/
# LEGACY_AND_DEAD_CODE.md) that predates this change and is out of this
# task's scope. Only the VerificationDocument.status choices addition
# (CORRECTION_REQUIRED) belongs to Phase 1.1.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0004_caregiverprofile_avatar_caregiverprofile_cover_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("correction_required", "Correction Required"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
