# Generated by Django 5.2.16 on 2026-07-15 07:33
#
# Hand-curated: the auto-generated migration also proposed AlterField
# operations for caregiverprofile.bio, companyaffiliationrequest.*,
# customerprofile.notes, and organizationprofile.address/code/description —
# pre-existing, unrelated Meta-representation drift present since before
# this phase (see project docs/traceability — every prior phase's
# `makemigrations --check --dry-run` reports the same cosmetic drift).
# Removed here per this phase's explicit migration policy: "exclude
# unrelated pre-existing migration drift." Only CaregiverSkill/
# CaregiverExperience (Phase 2.1's own new models) remain below.

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_add_correction_required_document_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaregiverExperience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("organization_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="accounts.caregiverprofile",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_caregiver_experience",
                "ordering": ["-is_current", "-start_date"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__isnull", True),
                            ("end_date__gte", models.F("start_date")),
                            _connector="OR",
                        ),
                        name="ck_caregiver_experience_end_after_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CaregiverSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_order", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="accounts.caregiverprofile",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_caregiver_skill",
                "ordering": ["display_order", "created_at"],
                "constraints": [models.UniqueConstraint(fields=("caregiver", "name"), name="uq_caregiver_skill_name")],
            },
        ),
    ]
