# Generated by Django 5.2.16 on 2026-07-15, hand-curated.
#
# The auto-generated migration also proposed AlterField operations for
# caregiverprofile.bio, companyaffiliationrequest.*, customerprofile.notes,
# and organizationprofile.address/code/description — pre-existing,
# unrelated Meta-representation drift present since before this sprint
# (see project docs/traceability — every prior phase's
# `makemigrations --check --dry-run` reports the same cosmetic drift).
# Removed here per this repository's established migration policy:
# "exclude unrelated pre-existing migration drift." Only
# CaregiverGalleryItem (this sprint's own new model) remains below.

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.accounts.models.media_paths


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_caregiver_skill_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaregiverGalleryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=apps.accounts.models.media_paths.caregiver_gallery_path),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("display_order", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_items",
                        to="accounts.caregiverprofile",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_caregiver_gallery_item",
                "ordering": ["display_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["caregiver", "display_order"],
                        name="accounts_ca_caregiv_b60e2f_idx",
                    )
                ],
            },
        ),
    ]
