# Generated by Django 5.2.16 on 2026-07-16 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_caregiver_gallery_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="terminated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="terminated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="termination_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="caregiverprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="companyaffiliationrequest",
            name="caregiver_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="companyaffiliationrequest",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="affiliation_requests",
                to="accounts.organizationprofile",
            ),
        ),
        migrations.AlterField(
            model_name="companyaffiliationrequest",
            name="reviewer_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="organizationprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="organizationprofile",
            name="code",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="organizationprofile",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
