# Generated by Django 5.2.16 on 2026-07-16 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_company_affiliation_termination"),
        ("kernel", "0011_role_assignment_active_scope_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organizationmembership",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="closure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "invitation_declined_by_caregiver",
                        "Invitation declined by caregiver",
                    ),
                    (
                        "invitation_cancelled_by_company",
                        "Invitation cancelled by company",
                    ),
                    ("terminated_by_company", "Terminated by company"),
                    ("left_by_caregiver", "Left by caregiver"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="companyaffiliationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("caregiver_profile",),
                name="uniq_pending_affiliation_request_per_caregiver",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role_type", "caregiver"), ("status", "active")),
                fields=("user",),
                name="uniq_active_caregiver_membership_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "active"])),
                fields=("organization", "user", "role_type"),
                name="uniq_open_membership_per_org_user_role",
            ),
        ),
    ]
