# Generated by Django 5.2.16 on 2026-07-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_organizationmembership_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationprofile",
            name="headline",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
