# Generated by Django 5.2.16 on 2026-07-16 16:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_organizationprofile_headline"),
        ("kernel", "0011_role_assignment_active_scope_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="accounts.customerprofile",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="kernel.servicesupplier",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_favorite",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer_profile", "-created_at"],
                        name="idx_favorite_customer_created",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer_profile", "supplier"),
                        name="uq_customer_favorite_supplier",
                    )
                ],
            },
        ),
    ]
