# Generated by Django 5.2.16 on 2026-07-09 16:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.orders.models


class Migration(migrations.Migration):
    dependencies = [
        ("kernel", "0010_useraccount_email_unique"),
        ("orders", "0005_tenant_foreign_keys"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderShareLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=apps.orders.models._generate_share_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Link stops working after this time, even if never revoked."),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.IntegerField(default=0)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="orders.order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_share_links",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "orders_share_link",
                "ordering": ["-created_at"],
            },
        ),
    ]
