# Generated by Django 5.2.16 on 2026-07-10 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_elderprofile_allergies_and_more"),
        ("kernel", "0010_useraccount_email_unique"),
        ("orders", "0006_ordersharelink"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderOrganizationEligibility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("withdrawn", "Withdrawn")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="manual",
                        help_text="Always 'manual' in this Epic — every row is an explicit grant() call. Plain string, not an enum: constraining it now would be speculative.",
                        max_length=20,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_eligibilities",
                        to="orders.order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_eligibilities",
                        to="accounts.organizationprofile",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_organization_eligibilities",
                        to="kernel.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "orders_organization_eligibility",
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "order", "status"],
                        name="idx_orgelig_tenant_order_st",
                    ),
                    models.Index(
                        fields=["tenant", "organization", "status"],
                        name="idx_orgelig_tenant_org_st",
                    ),
                ],
                "unique_together": {("order", "organization")},
            },
        ),
    ]
