# Generated by Django 5.2.15 on 2026-07-13 18:37
# Squashed: combines initial creation with canonical uniqueness constraint.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kernel", "0011_role_assignment_active_scope_constraint"),
        ("orders", "0007_order_organization_eligibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderOffer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("price_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="IRR", max_length=10)),
                ("estimated_duration_minutes", models.IntegerField(blank=True, null=True)),
                ("terms", models.TextField(blank=True)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("selected", "Selected"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("withdrawn", "Withdrawn"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("selected_at", models.DateTimeField(blank=True, null=True)),
                ("hold_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="offers", to="orders.order"
                    ),
                ),
                (
                    "selected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_offers",
                        to="kernel.servicesupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="order_offers", to="kernel.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "orders_order_offer",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "order", "status"], name="idx_offer_tenant_order_st"),
                    models.Index(fields=["tenant", "supplier", "status"], name="idx_offer_tenant_supplier_st"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("order", "supplier"), name="uq_order_offer_one_per_supplier"),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "selected")),
                        fields=("order",),
                        name="uq_order_offer_one_selected_per_order",
                    ),
                ],
            },
        ),
    ]
